apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-java-app
  labels:
    app: java-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: shopping-cart
      tier: java-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1    
  template:
    metadata:
      labels:
        app: shopping-cart
        tier: java-app
    spec:
      containers:
      - image: robudex17/shopping-cart:prod
        name: java-app
        imagePullPolicy: Always   
        ports:
        - containerPort: 8080
          name: java-app

