apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-java-app
  labels:
    app: java-app 
spec:
  selector:
    matchLabels:
      app: shopping-cart
      tier: java-app
  template:
    metadata:
      labels:
        app: shopping-cart
        tier: java-app
    spec:
      containers:
      - image: robudex17/shopping-cart:prod
        name: java-app
        ports:
        - containerPort: 8080
          name: java-app

