apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-mysql
  labels:
    db: mysql 
spec:
  selector:
    matchLabels:
      app: shopping-cart
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shopping-cart
        tier: mysql
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: nodetype
                  operator: In
                  values:
                    - database
      containers:
      - image: mysql:8.0
        name: mysql
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret 
              key: mysql-db
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: my-pvc

