name: Shopping Cart Action 

on: workflow_dispatch #manual trigger 
jobs: 
  TestingCode: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Code Checkout 
        uses: actions/checkout@v4 
      - name: Echo Github Action
        run: echo "Hello Github Actions"
    
